services:
  app:
    container_name: dashlit-app
    image: ghcr.io/codewec/dashlit:latest
    restart: unless-stopped
    environment:
      ORIGIN: '${ORIGIN:-http://localhost:3000}' # please provide URL if different
    ports:
      - '3000:3000'
    volumes:
      - ./data:/app/data
